name: Pester

on:      
  workflow_dispatch:

jobs:
  build:
    name: Pester Test
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/powershell:latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Perform all Pester tests from the pester folder
        shell: pwsh
        run: |
          Install-Module -Name Pester -Force
          Import-Module -Name Pester
          Invoke-Pester -Path "./tests/*" -Passthru
          
    if: ${{ always() }}
