name: Psscriptanalyzer

on:     
  workflow_dispatch:

jobs:
  build:
    name: Psscriptanalyzer
    runs-on: self-hosted
    container:
      image: mcr.microsoft.com/powershell:latest

    permissions:
      contents: read
      packages: read
      statuses: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: ./ # Uses an action in the root directory
        with:
          recurse: true
          output: results.sarif
          enableExit: true
